[package]
name = "hello_api"
version = "0.1.0"
authors = ["Adam Wright <shaladdle@gmail.com>"]

[dependencies]
#tarpc = { path = "../../" }
#tarpc-plugins = { path = "../../src/plugins/" }

tarpc = "0.9.0"
tarpc-plugins = "0.2.0"

serde = "1.0"
