[package]
name = "service_api"
version = "0.1.0"
authors = ["Kenjiro Nakayama <nakayamakenjiro@gmail.com>"]

[dependencies]
tarpc = "0.9.0"
tarpc-plugins = "0.2.0"
serde = "1.0"
serde_derive = "1.0.21"